### ISSUE TITLE
Extend JobView util to show configured CPU limits

### ISSUE THREAD

**Issue by astryia** [zodiacon/KernelExplorer#2]
Hello

Could you please extend JobView utility to print JOBOBJECT_CPU_RATE_CONTROL_INFORMATION.
It would help to dig into the Windows containers implementation.

Thanks.

**Comment by zodiacon** [comment]
You can see this info in the SysExp.exe tool in my AllTools repo.

**Comment by astryia** [comment]
It's awesome. Thank you.
